---
name: FiberedMySQL2 Gem Build
on: [push, pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2]
        gemfile:
        - Gemfile
        - gemfiles/rails_6.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.29
        bundler-cache: true
    - run: bundle exec rspec
